name: Greetings

on:
  workflow_dispatch:

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello with Timestamp
        run: |
          while true; do
            echo "Hello - $(date)"
            sleep 5
          done