name: Happy Weekend Greeting

on:
  schedule:
    # Triggers at 1:05 AM UTC on Monday, which is 8:05 PM EST on Sunday
    - cron: '5 1 * * 0'  # Change the day of the week to Sunday (0)
    
jobs:
  print-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Print Happy Weekend with Timestamp
        run: |
          echo "Happy Weekend! Current Timestamp: $(date)"