name: Happy Weekend Greeting

on:
  schedule:
    - cron: '5 1 * * 1'  # Triggers at 1:05 AM UTC, which is 8:05 PM EST on Sunday

jobs:
  print-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Print Happy Weekend with Timestamp
        run: |
          echo "Happy Weekend! Current Timestamp: $(date)"